* 2021/07/18 (日)
ツイッター API について調べよう。
https://developer.twitter.com/en/docs
https://developer.twitter.com/en/docs/tutorials/step-by-step-guide-to-making-your-first-request-to-the-twitter-api-v2

- ツイッター API でツイートを投稿したり、取得したりできる。
- ツイッター API を使うにはデベロッパーアカウントが必要。
- スタンダードと学術研究用（academic research）がある。学術研究用の場合アクセス回数の上限とかが増えるらしいけどよくわからない。

https://developer.twitter.com/en/portal/projects/new

とりあえずプロジェクト作ってみる。
色々聞かれるが適当に入れとけばよさそう。
そこで止められるということはない。

キーがもらえるのでそれを使っていく。

#+begin_src bash
TWITTER_API_BEARER_TOKEN=xxxxxx
curl --request GET 'https://api.twitter.com/2/tweets/search/recent?query=from:eggc0 \
     --header "Authorization: Bearer $TWITTER_API_BEARER_TOKEN"
#+end_src

これで自分のツイートが取れるはず。結構簡単に使えて良い感じだ。

https://github.com/twitterdev/Twitter-API-v2-sample-code/blob/main/Tweet-Lookup/get_tweets_with_bearer_token.js

js を使うときはこんな感じだ。

* 2021/07/17 (土)
めちゃくちゃギルティギアした。
勝率6割くらいだったので気持ちよかった。
ラムレザルとの対戦は、リーチが違いすぎてまともに勝負できないので、水月のハコビを適当に使って荒らすしかなさそう。

* 2021/07/16 (金)
スクラムというかチームで働くというのがめちゃくちゃ難しい気がしてきた。
* 2021/07/15 (木)
結構ストレスかかる仕事を切り抜けた。
このあともあるけど、とりあえず一息。

この話結構いいなと思った。

> デヴィッド：日本の特色というのは、フローチャートでも確かにあります。まず一番にくるのは、共感能力です。選択肢において、共感を必要とするチョイスは、日本人がぐっと高いんですよ。それは、アンドロイドの立場になって共感するのも、人間の立場から共感するのも同じ傾向です。

> デヴィッド：そうです。例えば、エンディングのほうでカーラがバスのチケットを見つけるシーンがありますが、あのチケットの持ち主は赤ちゃんがいる若い人間の夫婦じゃないですか。カーラがチケットを手にしたあと、その夫婦が戻ってきてチケットをなくしてしまったと取り乱す場面で、夫婦にチケットを返すかどうかという選択肢が出現するわけですが…大抵の国では、チケットを返すのが大体40％、自分のものにしてしまうのが60％くらいなんです。なのに、日本は85％が返すんですよ。他の国の2倍以上の人が、人間の夫婦のほうに同情をして、チケットを返してしまうんです。

https://www.gamer.ne.jp/news/201909170030/

* 2021/07/14 (水)
仕事明けてから夢中でアークナイツ。
とにかくイフリータでめちゃくちゃにするという方針でやった。
それが正しいかどうかはわからないけど自分なりのやり方で鉛封契約勲章Ⅱが取れたので満足。
* 2021/07/13 (火)
副作用で微熱がでてあまり集中できない。ぐったりする感じ。

* 2021/07/12 (月)
コロナワクチン接種。書類で色々トラブったので各所に連絡したりして疲れた…。

* 2021/07/11 (日)
カレードリア少なかったので2個食べてしまった。
車の練習で近くの駅とか行ってみた。まだまだ慣れない。
オッドタクシー最後まで見た。脚本がすごかった…。

* 2021/07/10 (土)
オッドタクシー10話分くらいみた。
日常ものかと思ったら色んな謎がでてきて引き込まれた。
あと闇が深い。

* 2021/07/09 (金)
白夜極光のイベントただ周回するだけでつまらない感じがする。

* 2021/07/08 (木)
目標設定するの結構憂鬱だな。
何を目指すべきか。よそ行きの目標を考えてしまう。
真心はどこだ。
* 2021/07/07 (水)
* 2021/07/06 (火)
２年くらい一緒に仕事してきた若者が出世して名古屋に行くらしい。びっくりだ。
ほんとに。二人チーム解散だなあ…。

* 2021/07/05 (月)
豪雨
* 2021/07/04 (日)
* 2021/07/03 (土)
公園に連れて行ってもらい、そこで駐車練習した。
* 2021/07/02 (金)
* 2021/07/01 (木)
アウトローがめちゃくちゃしている場所とか文化的に知らんこと多いな。
* 2021/06/30 (水)
とにかく関心を持ってほしくて、相手が望んでないものを上げてしまったりとかしたこと思い出す。
つらすぎる。受け取る側としてもつらすぎる。
* 2021/06/29 (火)
* 2021/06/28 (月)
* 2021/06/27 (日)
* 2021/06/26 (土)
車に乗ったけど駐車がうまくできなかった…。
動画見て勉強してみよう…。

* 2021/06/25 (金)
失敗を語るのは難しい。
今まさに失敗していることを語るのは、さらに難しい。

* 2021/06/24 (木)
小さな問題がたくさん転がっていて、そこには感情のゆらめきがある。
怒り、不満、いらだち。それは悲しいことだが今はただ良い仕事をするように努力する。
少しずつ良いことを重ねていけば理想の未来につながっているにちがいない。

* 2021/06/22 (火)
yama あるいは映画のような

皆が頑張った結果です。とても素晴らしかった。
そう言われるのはかすかに嬉しい。
そういうことが大事なんだと思う。

* 2021/06/21 (月)
全然仕事うまくいかない。疲労する。

* 2021/06/20 (日)
記事検索の機能がほしい。
とりあえず記事一覧を react-select 使ってみよう。
きれいなピラミッドになるように設計見直してみよう。

* 2021/06/19 (土)
車の話でちょっと揉めてあまり眠れなかった。
ギルティギアやってたら面白くて更に眠れなかった。

* 2021/06/18 (金)
出社してつかれた。
普段会わない人と会えたので行ってよかった。

* 2021/06/17 (木)
悩みの多い日常。
久しぶりに人から褒められて嬉しかった。

* 2021/06/16 (水)
プログラミングなんもわからん。

* 2021/06/15 (火)
コード再利用のためにモジュールを使ってはいけないのかもしれない。
問題を解きほぐすためにモジュールを使うのはよい。

* 2021/06/14 (月)
水槽「ゴーストの君」という歌格好良いな。
手嶌葵の声がとても優しい。

* 2021/06/13 (日)
午前中はゲームしてから、昼はカレーを食べに出かけた。
チーズナンセットを食べたら腹がはち切れそうになった。
食べすぎて気持ち悪くなり、満腹状態が半日くらい続いた。
将棋のamebaトーナメントの解説動画とか、
どぐらのクソキャラ列伝を眺めてボーッとしてから
Netflix で「ヒナまつり」を何話か立て続けに見た。面白かった。
夜はサラダとアイスクリームだけで済ませた。

* 2021/06/12 (土)
No man's sky を時々遊んでいる。星の広さに呆然としてしまう。

本当に楽しめるのか不安を感じながらもギルティギアstriveを買った。
定価で買ったので8000円以上した。一応楽しく遊べている。

* 2021/06/11 (金)
会社の部会が5〜6時間あり、かなりしんどかった。
人間が協力するためにはお互いのことを知る必要があるというのは理解できる。
けれど、外部からそれを強制されるのは息苦しい感じがする。
どうすれば苦しまずに、自然とよい関係性を作ることができるのだろうか。

* 2021/06/10 (木)
また、がむしゃらに働いた。空き時間で次の仕事の進め方を考えていたけどうまく整理できなかった。
新しいものを作るよりも、古いものを作り変えるほうが難しい。

* 2021/06/09 (水)
進撃の巨人最後まで読んだ。
暴力・アクション・サスペンスで、山盛り面白かったと思う。
巨人の強さが理不尽で、めちゃくちゃになっている。
絶望の深さと、叫び、抵抗する姿に動かされる。
伏せられていた謎は、丁寧に説明されるので納得する。
そのあたりは、すごい練り込まれているなあと思った。

ただ、壁の外の世界はあまり好きじゃなかった。
一つには理解できない・好感を持てない人物が多いということ。
破滅的な思想をもっていたり、欲望が強すぎたり、エゴイストが多いので疲れる。
そして、政治と戦争の話がくどい。ほとんど人物を描いてないから興味を持てない。
国同士の衝突は現実的だけど、見たくもない世界情勢のニュースを見せられているような感じもあった。
あとは、主役のエレンの出番が減って、国の対立構造を描くために
頻繁に場面が変わって頭が混乱するというのもあった。
一気に読んだからかもしれない。

* 2021/06/08 (火)
やりたいことが決まっていたのでひたすらに仕事をした。
育児休業のことが気になり始めている。

* 2021/06/07 (月)
姉夫婦と会うことになった。自分は、何のために会うのか？
どういう態度をとるべきか？　考えてはみたけれど、結論のないまま対面した。
職場にパンを欲しがる変な男性職員がいるという話が面白かった。
勝手にパンを盗んだりして当然のような顔をしているらしい。
聞いているだけなら理不尽さが笑えるけれど、実際そんな目にあったら不快感すごそうな気もする。

* 2021/06/06 (日)
会社の広報を清らかな心で見ることができない。
猜疑心が強い。見えない側面に汚れが詰まっているのではと思ってしまう。

* 2021/06/05 (土)
進撃の巨人を読んだ。

技術者の間では「マサカリ」という文化がある。
間違っている主張に対しては、厳しく批判するべきだと言う考え方だ。
プログラムを批判して、書いた人を批判しないようにする。
批判された人もそのように解釈するように努める。
だがそれはいつもうまくいくわけではない。

自分が生み出したものが批判されれば、ほとんどの人は悲しい気持ちになる。
プログラムを書く人はみないつもそういう衝突を繰り返している。

* 2021/06/04 (金)
自分にとってよいことが、他人にとってもそうであるとは限らない。
現実を目の当たりにして打ちひしがれる。うーん。派閥という問題。

自分の利益を最優先してプログラムを書くということは不可能だ。

flycheck を動かしたいので rubocop をグローバルインストールしてみる。

* 2021/06/03 (木)
自分を攻撃するような批判者が現れたときの対処は難しい。
自分を守るために目がくらむ。

* 2021/06/02 (水)
手持ちのカードで勝負するしかないと言う話。悔しい。
理想の人はいつまでも見つからないという話にも似ている。

* 2021/06/01 (火)
なんか、虚しい。仕事する気が失せているかも。
なんか、ではなく理由があって虚しいのだがその理由を説明することは難しい。

* 2021/05/31 (月)
ユーザIDとパスワードを移譲してスクレイピングをするサービスが、不正アクセスと認知された件について。これはまあ、スクレイピングをやめたほうがおおきな理由の一つだろうな。

「アイラヴミー」「ゆある」「あたらよ」とか聞いてみよう。

* 2021/05/30 (日)

スクリプト言語を触っていた時間が長すぎて、
コンパイル言語はいちいちコンパイルしないとエラーを見つけられないから面倒だと思っていた。
けれど、最近のエディタならバックグラウンドで擬似的なコンパイルを実行するから、
ほとんど待ち時間なしにエラーを見つける事ができる。
emacs も flycheck で似たようなことができる。
実際体験してみると、ほとんどストレスがない。
プログラムを実行せずともエラーが出るわけだから、悪くない体験だ。

* 2021/05/29 (土)
善意しかないのに、それが伝わらないというのはとても悲しいことだ。
そういう態度もまた身勝手であることは違いない。
偶然見てはいけないものを見た。陰口は、やめてくれ。
たぶんそういう意図はないんだろう。関わらないことが最善。
成人は、変化させることができない。

* 2021/05/28 (金)
理由なく何かを徹底的に避けたり嫌ったりすることは愚かだ。
なぜならそこにある利益を見逃すからだ。
けれども、嫌いなことに向き合うというのは、いつも本当に本当に難しい。本当に。

* 2021/05/27 (木)
悔しいけど、人脈ないし、広報する力が弱すぎる。

仕事をしていく上で、その人が面白いかどうかは大事じゃないんだなと言うのを思った。
信頼できるか、本音で話すことができるか。それだけ。
どんなにつまらなくてもたいして問題はない。
信頼に結びつくのは、逃げないことと、向き合うことと、小さな積み重ね。

* 2021/05/26 (水)
長年勤めている会社で、外部から入社した人が上司になると、反発する心がでてくる。
年齢とかじゃなくて、その人の能力を認めていないと言うか。
それは会社でなかったとしてもそうだ。

https://twitter.com/koujounodenki/status/1397188516044541955

この問題、下から2桁目が A と B を足して B のままになっているというのが糸口になっていておもしろい。

* 2021/05/25 (火)
なんかわからないけど、自尊心が爆発していた。
なんかめんどくさいとかうまく行かないとかそういうのばかり気づいて、
仕事を楽しむということを忘れていたような気がする。

悪いことに目を向けるというのも無駄ではない。
ただ、良いところに目を向けて生きていくほうが楽だろう。
周りに囚われてはいけない、いろいろな人がそう言っている。
けれどそれが、とても難しいことなのだ。

* 2021/05/24 (月)
大切にしていることを手放してはいけないと思った。
軽い気持ちで人に任せると、それは自然と変形し、潰れていってしまう。

論文書けば書くほどわからなくなる状態。
そういうときはだいたい、現状把握か、主張したいことが正しく認識できてない。
具体的にする。何をどうしたいのか、もう一度見直す。そして、複雑な問題は小さく分解する。
傍らにいる誰かに語りかけて、説得できるかと想像してみる。

* 2021/05/23 (日)
自分だけが損をして人にものを与えるのは、単なる自己犠牲でそれはよくないそうだ。
与え合い、お互いが得をするような関係を作れる人が成功するのだという。

先行投資はいつも損をするように見える。

* 2021/05/22 (土)
長距離散歩して、鎌倉パスタで1500円くらいの生パスタを食べた。

好きか嫌いかというのと、良いか悪いかというのがつねに対立している。

* 2021/05/21 (金)
久しぶりに出勤。今まで好きだったカレーを食べたら、辛すぎてあまり美味しさを感じなかった。

女の園の星、面白い。

エルフと狩猟士のアイテム工房、平和でよかった。
今はそういう、敵のいない世界を望んでる。

* 2021/05/20 (木)
プログラマ以外と一時間ほど会話する交流会の日。

面倒だし、他部署には興味がないのでやりたくない。
段取りも良くなかった。担当者が不在で、司会をやる人がいなかった。

そういえばこういう行事は昔の会社でもやっていたなと思い出す。
こういう場面で、人の機嫌を取ろうと動いていたが、簡単なことではない。
うまく行かないこともあるし、それなりに疲れる。
今日はただ静観していようと思った。

ビデオ会議に、暗い顔をした男たちが三人集まる。
入社して四日目のメンバーもいた。沈黙が耐えられなくて、話を切り出す。
お互い様子を伺いながら、どうでもいい話をする。本音で話さない。
いつだってこういう時間があるのは仕方がないけれど、慣れない。

* 2021/05/19 (水)
職場で、自己評価の日。

チーム全員にプラスが有るような取り組みを考えていた。
プログラムに関するドキュメントを作っていこうという考えだ。
誰からも反対はされなかったけれど、何もコンテンツが増えなかった。
どういうものが作りたいとか、どういう風に作っていくのかビジョンが弱かったのだと思う。
そして、誰かの心を動かすというのは難しいと思った。
強い情熱があるなら、自ら主導していくという可能性もあるかもしれないが、今の自分にそれはない。
少ない負担でよい成果が得られるようなものを考えたい。

昔七年間働いた職場で、受け身であることが、弱みかもしれないと指摘を受けたことを思い出す。
そのとおりに違いない。その傾向は長い時間で醸成されたものなので、急に変えることはできない。
そのなかでうまくやる方法を探していくしかない。

* 2021/05/18 (火)
警察で事情聴取を受けた。

* 2021/05/17 (月)
妻が交通事故にあって救急車で運ばれた。エアバッグは起動しなかったらしい。
いま、救急車で運ばれているよ、と自ら電話をかけてきたので驚いた。
深刻な声色と、背後で鳴っているサイレンが、冗談ではないことを証明していた。
ただ動揺した。どうすればいいのか、わからなかった。

急ぎ病院に向かったところ、意識ははっきりしているし、会話も問題がなかった。
しかし、スカートに血痕がついていたり、首筋にシートベルトの形をした痣ができていた。
一緒に帰って、出前の寿司を頼んだ。

* 2021/05/16 (日)
go のパッケージの作り方を勉強した。

* 2021/05/15 (土)
「うちの使い魔がすみません」面白かった。

* 2021/05/14 (金)
Loop Hero クリア。ネクロマンサーでスケルトン関連のスキルを集めるといける。
沈没船とか血の森作らなければ安定していける。

* 2021/05/13 (木)
詳しくなったけどあんま意味なかったな、ということがある。
きっとそれは役に立ちますよと慰められるという経験も、同じくらい多い。

* 2021/05/12 (水)
Loop Hero すべての地形がオープンされた。
あとは最終ステージをクリアするのみ。

* 2021/05/11 (火)
「仲良くする」ということは「仲良くしない人」をはじき出すということなのかもしれない。

* 2021/05/10 (月)
Loop Hero おもしろすぎる。
slack チャンネル多すぎると思って、離れることにした。

* 2021/05/09 (日)
Go の勉強少ししてあとは Loop Hero を遊んだ。

* 2021/05/08 (土)
まあまあ面白い導入だったはずなんだけどつじつまを合わせていくと
なんだかありそうな話に着地してしまって、驚きがなくなってしまった。

亜人の最終巻見た。やっと決着。結局、佐藤の物語になってた。

* 2021/05/07 (金)
Loop Hero 買った。めちゃくちゃおもしろかった。

* 2021/05/06 (木)
変なバグの対処方法探しててめちゃくちゃ疲れた。

* 2021/05/05 (水)

灼熱カバディを読んで、脳が茹で上がるほど興奮した。
公園まで歩いた。1万歩になった。最終日だと気づいて絶望した。

また、物語を考え始めた。
あらすじはまあ良いんだけど、文章にしてみると具体的にしてみると、
その情報の頼りなさに不安になる。
本物を知らない人間が、上辺の情報で取り繕っているというのが透けて見える。
これはこまった。それが本質ではないのに。
でも、それを消してしまったら、疑問の余地が生じるのではないか。

* 2021/05/04 (火)
セブンを見た。クロノトリガーやフロントミッションの話をした。

* 2021/05/03 (月)
眠くてしかたがなく、横になっていった。何もしなかったという深い罪悪感にとらわれている。
ロックマンXと、ポケモンスナップのRTAを見た。

* 2021/05/02 (日)
アークナイツとチェンクロ進めて、ビッグフィッシュ見た。

* 2021/05/01 (土)
サイトのレイアウト調整。

* 2021/04/30 (金)
待ちわびたアークナイツのアップデート。
ガチャ70回くらい回したらロスモンティスとマドロック両方手に入ったので満足して日常に戻った。
マドロックはもっと激渋い男をイメージしてたのでなんとも言えない気持ちになる。美少女すぎた。
男がほしいとは別に思ってないが頭の中で持たざるものイメージしてたので抵抗感がある。

* 2021/04/29 (木)
祝日。長めの散歩にでかけた。
公園を一周した後、まんじゅうを買って、その後とんかつ屋に入ってみた。
上ロース定食を頼んで、持ち帰ることにした。油っ気がなくて淡白な肉だった。
これで5000歩くらいになった。

暇だったので塊魂をインストールして遊んだ。
その後ショップを眺めていたらKingdomシリーズに続編がでていたというのを知り、買いたくなった。
その心を抑えてKingdom: new landsを起動した。いくつか実績を集めた。50日前後で倒れてしまった。
大型のモンスタがー強すぎて抑えきれない。

* 2021/04/28 (水)
DMMカードが還元率4%だったり、5000ポイント付与だったりしていたので申し込みしてみた。
そしてDMMブックスの50%還元セールを使って少しだけマンガを買った。
すでに大量購入してしまったkindleがあるので辛いけどamazonで買うよりはお得なので乗り換えよう。

ついでにamazonカードも申し込みしてみた。amazonは2%だけどDMMでは買えないものがあるから。

* 2021/04/27 (火)
面接官をした。会話をしながらこの人は合格を出せないな、と思ってしまった。
早々に結論を出してしまうのは良くない。

* 2021/04/26 (月)
チェーンソーマンを読んだ。想像を遥かに超えて来た。面白かった。

* 2021/04/25 (日)
goの勉強でやっとインターフェースとかの話が終わった。
クラスとかインスタンスという言葉が使えないのが不便でしかたない。

朝六時くらいに起きてしまったあと、二時間くらい昼寝していた。

* 2021/04/24 (土)
来客に備えてカーペットを新調することにした。
お下がりは仕事部屋に来る予定。
ついでにワイヤレスキーボードやワイヤレスマウスを買った。
なので楽しみだ。散財まっしぐら。

* 2021/04/23 (金)
自己紹介するのが辛いと思った。
大したことのない自分のことを話さなければならないというのが、他との差を感じてつらい。
一般受けされるような趣味は持ってない。読書とか料理とか旅行とかしない。
自分の世界に閉じこもっているだけだ。別段面白いものでもない。
掘り下げられると困るから、言えないことばかりになる。
結果、秘密主義の人みたいになってしまった。

家族という逃げ場所があるのは本当にありがたい。

* 2021/04/22 (木)
githubのプルリクエストを作るときに、エラーが出るようになってしまった。
こういうときEmacsを使うことにちょっとした絶望を感じる。
メンテナンスしている人が個人なのでいつ修正されるかもわからない。
自分で治せるくらいlispの理解があればよいのだが。

* 2021/04/21 (水)
Releaseトラブルが予想されたがとりあえず平穏に終わった。

殴られすぎて痛みに鈍感になったというエピソードを聞いた。
麻酔とかも効かない体質らしい。

* 2021/04/20 (火)
理由なき行いを減らしていくのがプロ？

些細なことでお互いを傷つけないように、貯金していくものが信頼、なのかも。

* 2021/04/19 (月)
退去費用、清掃費用、エアコン掃除費用とかなり請求されてしまった。
契約書に書いてあるのでと言われるが、納得した上で契約してないので非常に悔しい。
相手の事情とか関係なく、自分が不利益を被る話になると、途端に苛つくのは間違いない。
特に、何の縁もないビジネス上の取引関係だと、義理や人情で慮ることがなくなる。
そういうとき自分の幼さを知る。普段は、たいして怒らないつもりでいるけれど、
「好きでもない人のために、やらなくていい仕事が増える」のにすぐ怒ってしまう。
恩を売るとか、そういう意味合いはあるはずなのだが、想像力が及ばない。
自分が、本質的に優しくないということの証拠だ。

サービスでつけた機能であってもそこに不具合があればユーザにストレスを与える。
そしてバグだというフィードバックが帰ってくる。
親切心が裏目に出るということ。よくあること。

* 2021/04/18 (日)
子供のように思われるかもしれないが、感情をケアしてくれと表明することも大事。
ただその一方で、関わりのある人の感情も想像する事が必要。

自分に責任はないと考えることで苦しみから逃れられるなら、それでいいはず。
でも、それによって被害が拡大していくのを目の当たりにしたら、耐えられない息苦しさになるだろう。

* 2021/04/17 (土)
やりたいことがなくてボーッとしていると、満腹状態なのに何かを口に入れたくなって、カップラーメンをすすってしまう。

* 2021/04/16 (金)
目標をたてないから、失敗したかどうかわからない。反省もでてこない。改善されない。という指摘になるほどと思った。

* 2021/04/15 (木)
ふとしたことに孤独を感じる。

* 2021/04/14 (水)
お金をつかう。明るい緑色のカーテンを選んだ。クッションはヨギボーにした。机はオカムラ家具。

* 2021/04/13 (火)
退居作業。

* 2021/04/12 (月)
引っ越し作業。

* 2021/04/11 (日)
せっせと荷造り。冷蔵庫を空にして電源を抜く。いままで一番たくさん洗濯機を回す。
風呂入った後は、タオルとかを片付けて、明日の朝にはカーテンを外して、布団を畳んで、蛍光灯を外す。
それでおしまいだ。

運び出すだけで済むように、少し掃除もしておこうか。

* 2021/04/10 (土)
go-playgroud を調べる。

* 2021/04/09 (金)
青葉とネギと水菜の組み合わせ良さそうに見える。

普段言わない人が言うことが大事にされるのかもしれない。

嫌いな人でも悲しそうにしてたら可愛そうと思うのは普通。

* 2021/04/08 (木)
ラジオ番組に応募したことが３回あって、ぜんぶ読まれている。結構話をふる才能あるのでは。

* 2021/04/07 (水)
ハナクソには内から排出されたものと、外から侵入したものとがある。

* 2021/04/06 (火)
まあまあ早く起きた。頑張った。

* 2021/04/05 (月)

* 2021/04/04 (日)
真面目にインライン数式に対応した。 $f(x)=x^2+4$ こんなふうに書ける。ただそれでも mathjax 数式に日本語を埋め込むと表示が壊れる。フォントがおかしいのだろうか。mathjax 3 ではフォントをサポートしてないらしい。それが原因かもしれない。

* 2021/04/03 (土)
会社は共同体ではあるけれど、愛を捧げる対象ではありえないと思っている。だから、仕事をうまくやるための努力はするけれど、気乗りしないことはなるべくやらない。

* 2021/04/02 (金)
悩み相談をしているときは、聞き手は答えを出さないほうが良いらしい。悩んでいる人自身が答えを出すことが大事なのだそうだ。

採用面接について。せっかく応募してくれた人を不合格にしてしまった。応募した人がその後どうするのかはわからないが、きっと落胆しているに違いない。もしかするとそれによって人生が大きく変わってしまったかもしれない。そういう責任の重さを感じると、本当に正しい判断を下すことができただろうかと不安になる。その人の良いところを引き出し、観察することができていたか。今となってはわからない。限られた時間ですべてを知ることはできない。

まず一番最初には、採用とは全く無関係の世間話を五分ほどしたほうが良いだろう。普段と違う状況に慣らして落ち着いてもらうため、そしてお互い対等であることを示すためだ。その後、これからどういう観点で面接を評価するのかというのも少し触れておくべきと思う。たとえば、物事を説明する段取り、順序が適切かどうか。用語を正しく使うことができているか。といった点を見ていきますよと宣言する。リラックスしつつも、スイッチをオンにしてくださいということをお願いしておく。

* 2021/04/01 (木)
「死とは何か」みたいな本を読み始めた。眠すぎて落ちた。

* 2021/03/31 (水)
髪の毛が硬すぎて、てのひらの皮膚に髪の毛が刺さる。悲しい気持ちになる。

* 2021/03/30 (火)
なんか息苦しいなあ。

* 2021/03/28 (日)
orga は ~#+begin_export latex~ のコードブロックは解釈できない。ソースコード見た感じ [[https://github.com/orgapp/orgajs/blob/78231fb20b3bcba42663c21da11cb06f01cab711/packages/oast-to-hast/src/handlers/block.ts#L34][oast-to-hast/src/handlers/block.ts]] であれこれできたらうまくいきそうな気がする。しかしもとが typescript なので、簡単にパッチでどうにかするのは無理そう。小細工をして mathjax をねじ込み、数式対応できた。下のような感じ。

\[ y = f'(x) \]

インライン対応は無理。

* 2021/03/27 (土)
大刀洗のため池で桜を見た。

* 2021/03/26 (金)
仕事して散髪してから田舎に行くという強行スケジュール。

* 2021/03/25 (木)
Nさんは、飛び込む力と、受け止める力。この二つが凄い。

* 2021/03/24 (水)
しばらく go の勉強さぼってたけど再開しよう。

* 2021/03/23 (火)
データ構造が透けて見えるアプリケーションは、良い。操作を予想することができるから。

* 2021/03/22 (月)
赤ちゃんの科学という動画を見た。生後9ヶ月まではあらゆる言語、あらゆる人種を区別する顔認識能力があるらしい。そして学習の効率化のために、その能力はすぐに失われ、最もよく使われる言語と、よく見かける人種に対する顔認識だけを行なうようになるらしい。あと、赤子は無能ではなく、現象をよく観察しているらしい。物体が重力に従って下に落ちることとか。だから色んな人、言語、場所、風景など体験させてあげることが良いのだという。

* 2021/03/21 (日)
白夜極光というゲームのクローズドβテストに参加してみた。面白いと思ったけど飽きてきた。引越し準備のため掃除をした。まずダンボール二箱。ちょっとずつやる。

* 2021/03/20 (土)
3人で集まってボードゲームやった後、マスターなんとかという喫茶店で食事会した。折りたたみ傘を買って帰った。疲れたのでお湯はりして浴槽に入ったら腰の痛みが少し柔らいだみたい。

* 2021/03/19 (金)
人間の寿命が伸びるほど幸運も不幸も経験するので、最終的にはバランス良く経験してから死ぬのではないか。

* 2021/03/18 (木)
弁当シリーズの中では、イベリコ豚重はかなり美味いと思う。あとは野菜を。牛カルビ重は味が濃すぎる。

* 2021/03/17 (水)
フレンチクルーラーは400キロカロリーもあるのに美味しくはなかった。

* 2021/03/16 (火)
スタイルシートクラス名は意味を与えるよりも装飾と考えたほうがいいかもしれない。

* 2021/03/15 (月)
人間が好きなんだか、嫌いなんだかよくわからない。

* 2021/03/14 (日)
Dragon marked for death を12時間くらい遊んでいた。プレイがうまくなってきてLV55のキャラクターでLV90のラスボスを倒すことが出来た。巫女が強い。
* 2021/03/13 (土)

#+begin_src scss
@import "~bulma/bulma";
#+end_src

これの ~~bulma~ ってなんだ？ [[https://stackoverflow.com/a/39535907]] これか。
[[https://webpack.js.org/loaders/css-loader/#url][webpack css-loader]] の機能らしい。

#+begin_quote
To import assets from a node_modules path (include resolve.modules) and for alias, prefix it with a ~
#+end_quote
* 2021/03/12 (金)
あんまり仕事してないかも。

* 2021/03/11 (木)
みずみずしい体験に彩られた自己紹介を聞いて、華やかさに圧倒される。自分が小さくなったみたいな気持ち。これまでの自分の人生にこれほどのドラマがあっただろうか。いやない。

* 2021/03/10 (水)

好みは人それぞれだということがわかっているので、自分の好きなものをおすすめするということができない。

* 2021/03/09 (火)

全然親しくなく、興味もなく、関係性もない人の、面白い過去話。どれくらい興味を持てるか。

* 2021/03/08 (月)

golang のメモ取り始めた。

* 2021/03/07 (日)

- https://github.com/gregjacobs/Autolinker.js
- https://highlightjs.org/

を入れた。

* 2021/03/06 (土)
ソフトウェアのドキュメントは不確かなものだなと思う。あったほうがいいのか、なくてもいいのかよくわからなくなってくる。いや、passenger のドキュメントとか rails guide とかは有益だと思うけど、社内ドキュメントとかそういうのが難しい。書いていて不安になってくる。

マージナル・オペレーション16巻を読んだ。順当に終わった。もっと、ぐちゃぐちゃですべてが壊れていくような結末ではないかと予想していたけれど概ね平和裏に終わった。甘い理想を引き裂いて、悲惨な現実を突きつけてくる作品だと思っていたので拍子抜けした。ただ、登場人物たちにとっては、ベストエンディングだったかもしれない。

ゴールデンゴールド8巻を読んだ。面白いのか面白くないのかよくわからない。怖い話のようでいて、そうでもない気がする。誰かが悪だと決めつけるわけでもなく、ゆるゆる流れていってるような。

* 2021/03/05 (金)

brew が壊れているらしくて変なメッセージが出る。

* 2021/03/04 (木)
呪術廻戦の15巻を見た。渋谷事変すごい面白い。釘崎野薔薇の退場。東堂のメンタル強さ。真人の領域展開と変身。虎杖の精神的成長。「拍手とは魂の喝采」のくだり、ハンターハンターのパクリやんけと思ったけど、ギリギリそうでもないかもしれない。面白いからいいか。大ゴマ実に格好良い。見せ場多い。そして決着。満身創痍のところに夏油がでてきて無双しているけどこれどうやって倒すんだろう。五条先生復活するには早すぎるし。

* 2021/03/03 (水)
単純にワクワクさせられるのは、やっぱり見たことのないものとかありえないものについて話を聞く、見るときかもしれない。

* 2021/03/02 (火)
常時起動していた slack を、見るときだけつけるようにした。それでだいぶ余計な時間が減った気がする。かわりに、誰かと会話することがなくなってしまった。人間関係作っていこうという気持ちが消えて、忍者のように隠れている。

* 2021/03/01 (月)
会社の評価制度には「組織貢献」という評価軸があって、つまりは会社の誰かにプラスになるような行いを求められている。これはプログラマとしての平常業務と違って、「こうすればよい」という働き方が見えない。そういうふわふわしたことがちょっと辛い。ただ、そういう少し枠組みから飛び出した働きが認められる評価制度があるということが大事なのかもしれない。

* 2021/02/28 (日)
「岸辺露伴は動かない」のアニメを見た。アニメ化された話は本当に先が読めなかったり怖かったりして、引き込まれる。流石に面白い。

- 懺悔室：窮地に陥ってアイデアで切り抜けるというところがハラハラして面白い。オチも凄い。
- 六壁坂：これもピンチに陥ってるときのドキドキ感が凄い。執拗な責め。切り抜け方も凄い。
- 富豪村：怖い昔話的な悲劇の香りがする。トウモロコシの食べ方わからんというのに共感できる。丸く収まってよかった。
- ザ・ラン：筋肉に取り憑かれた若者が狂っていくのが怖い。それを否定しない岸辺露伴凄い。

* 2021/02/27 (土)
引越し見積もりその2。私服作業員風の人が来た。昨日の人よりも粗雑な印象で、単に部屋を見て見積書を置いていった感じ。値引きの話とか値段の根拠とかは一切口にしなかった。それでいて安くはなかった。結局、最初に見積もりに来てもらったところで契約することに決めた。

「はたらく細胞BLACK」の一巻と二巻を見た。人体や医学、不摂生の恐ろしさについて学べるところはある。でも、すごく受け入れがたい。理由は、赤血球、白血球に人格が有ることの理不尽さ。個性があることの不気味さ。精子とか肝細胞とかでてくるとゾワッとした。自分の肉体がもしそうであるとしたら、自分が他者を支配しているということになるのだろうか。わかりやすくはあるけれど、茶番に見える。

主人公（赤血球）が必死に酸素を運ぶのだけれども、その背景にあるものは生命活動に伴う現象でしかない。そこに心の動き、ドラマを混ぜ込むのは不純ではないか。そういう偽りの真剣さに騙されたくないという感情が障壁になって、読みすすめることに耐えられない。

* 2021/02/26 (金)
引越し見積もりその1。スーツを着たすごく丁寧な人が来た。名刺くれたりとか値段の内訳とか、丁寧に説明してくれた。しかし値段が高い。広告に出ている金額とかなりの差があると指摘したら、値引きしてくれた。かなり乗り気になったのだが、話が進むにつれて怖くなってきて、ごめんなさいと言ったら怒らせてしまった。カタンとかやってるときもそうだったけど、交渉本当に下手だなと思った。

* 2021/02/25 (木)
アークナイツのイベントが始まった。喧嘩大好き部族の出身で、破天荒な、最強の女と里帰りするという話。それだけでけっこう面白い。その喧嘩大好き村に機械を持ち込んだズィママとひと悶着ある。あまり暗くならず爽やかに終わってよかった。

ケオベの茸狩迷界はめちゃくちゃ難しくて面白い。今まで使ってない低レアオペレーターを育て直すきっかけになった。目を開かされるような思い。自分が試されている、乗り越えてやろうという情熱が湧き起こる。

* 2021/02/24 (水)
「一人でできるもん」みたいな自尊心がときどき顔を出す。これを制御していきたい。

* 2021/02/23 (火)
祝日。Dragon marked for death を友人と二人で遊んでいた。動かしているだけで楽しいゲーム。グラフィックの品質としては、プレイステーション時代にでていそうなくらいだが、それが味わいがあって良い。

* 2021/02/22 (月)

あんまり仕事を割り振られないで、できることをやっていれば良いという境遇になっている。それは周りが優秀で頑張ってくれているからだ。とても良いことなんだけれど、チームの中に自分が入れてないような気がして少し寂しさも感じる。自分と活躍しているメンバーを比べると、ジメジメしている気がして。

* 2021/02/21 (日)

家探し。猫とドラゴン。

* 2021/02/20 (土)

寝ていた。

* 2021/02/19 (金)

目覚ましを無視してしまうくらい深い眠りに落ちていたらしい。気がついたときには昼休みの時間だった。予定していた打ち合わせをすっぽかしてしまっている。すっかり気が抜けて、現実を受け入れるまでに十五分はかかった。慌てて謝罪のメッセージを投稿し、そのまま会社を休むことを連絡した。昨日スーパーで買っておいたタイムセール握り寿司をパクパク食べて再び横になった。

ヨーロッパには、白鳥は死ぬときに美しい声で鳴くというという伝説が有るらしい。このことから swan song は遺作を表す比喩表現になったのだという。日本では全く使われないので何のことだかわからなかった。個人的には、白鳥の鳴き声は美しいというほどでもないと思う。

* 2021/02/18 (木)

担々麺屋へ足を運ぶ。券売機の前で、ずっと財布にひそませていた無料チケットを手にとった。お金を払わないのが申し訳ないので、トッピングしてサイドメニューも一品頼む。店員のおばさんが、明るい声でサービスしておくねと言い切った。促されるまま一円も払わずに席につく。待っている間に、無駄に嬉しくなって、この店の良いところを探してしまった。ラーメン屋というのは汚い場所が多いけどここの店はいつも清潔感あるな、と。いや、ちょろい。
