* 2021/03/06 (土)
ソフトウェアのドキュメントは不確かなものだなと思う。あったほうがいいのか、なくてもいいのかよくわからなくなってくる。いや、passenger のドキュメントとか rails guide とかは有益だと思うけど、社内ドキュメントとかそういうのが難しい。書いていて不安になってくる。

マージナル・オペレーション16巻を読んだ。順当に終わった。もっと、ぐちゃぐちゃですべてが壊れていくような結末ではないかと予想していたけれど概ね平和裏に終わった。甘い理想を引き裂いて、悲惨な現実を突きつけてくる作品だと思っていたので拍子抜けした。ただ、登場人物たちにとっては、ベストエンディングだったかもしれない。

ゴールデンゴールド8巻を読んだ。面白いのか面白くないのかよくわからない。怖い話のようでいて、そうでもない気がする。誰かが悪だと決めつけるわけでもなく、ゆるゆる流れていってるような。

* 2021/03/05 (金)

brew が壊れているらしくて変なメッセージが出る。

* 2021/03/04 (木)
呪術廻戦の15巻を見た。渋谷事変すごい面白い。釘崎野薔薇の退場。東堂のメンタル強さ。真人の領域展開と変身。虎杖の精神的成長。「拍手とは魂の喝采」のくだり、ハンターハンターのパクリやんけと思ったけど、ギリギリそうでもないかもしれない。面白いからいいか。大ゴマ実に格好良い。見せ場多い。そして決着。満身創痍のところに夏油がでてきて無双しているけどこれどうやって倒すんだろう。五条先生復活するには早すぎるし。

* 2021/03/03 (水)
単純にワクワクさせられるのは、やっぱり見たことのないものとかありえないものについて話を聞く、見るときかもしれない。

* 2021/03/02 (火)
常時起動していた slack を、見るときだけつけるようにした。それでだいぶ余計な時間が減った気がする。かわりに、誰かと会話することがなくなってしまった。人間関係作っていこうという気持ちが消えて、忍者のように隠れている。

* 2021/03/01 (月)
会社の評価制度には「組織貢献」という評価軸があって、つまりは会社の誰かにプラスになるような行いを求められている。これはプログラマとしての平常業務と違って、「こうすればよい」という働き方が見えない。そういうふわふわしたことがちょっと辛い。ただ、そういう少し枠組みから飛び出した働きが認められる評価制度があるということが大事なのかもしれない。

* 2021/02/28 (日)
「岸辺露伴は動かない」のアニメを見た。アニメ化された話は本当に先が読めなかったり怖かったりして、引き込まれる。流石に面白い。

- 懺悔室：窮地に陥ってアイデアで切り抜けるというところがハラハラして面白い。オチも凄い。
- 六壁坂：これもピンチに陥ってるときのドキドキ感が凄い。執拗な責め。切り抜け方も凄い。
- 富豪村：怖い昔話的な悲劇の香りがする。トウモロコシの食べ方わからんというのに共感できる。丸く収まってよかった。
- ザ・ラン：筋肉に取り憑かれた若者が狂っていくのが怖い。それを否定しない岸辺露伴凄い。

* 2021/02/27 (土)
引越し見積もりその2。私服作業員風の人が来た。昨日の人よりも粗雑な印象で、単に部屋を見て見積書を置いていった感じ。値引きの話とか値段の根拠とかは一切口にしなかった。それでいて安くはなかった。結局、最初に見積もりに来てもらったところで契約することに決めた。

「はたらく細胞BLACK」の一巻と二巻を見た。人体や医学、不摂生の恐ろしさについて学べるところはある。でも、すごく受け入れがたい。理由は、赤血球、白血球に人格が有ることの理不尽さ。個性があることの不気味さ。精子とか肝細胞とかでてくるとゾワッとした。自分の肉体がもしそうであるとしたら、自分が他者を支配しているということになるのだろうか。わかりやすくはあるけれど、茶番に見える。

主人公（赤血球）が必死に酸素を運ぶのだけれども、その背景にあるものは生命活動に伴う現象でしかない。そこに心の動き、ドラマを混ぜ込むのは不純ではないか。そういう偽りの真剣さに騙されたくないという感情が障壁になって、読みすすめることに耐えられない。

* 2021/02/26 (金)
引越し見積もりその1。スーツを着たすごく丁寧な人が来た。名刺くれたりとか値段の内訳とか、丁寧に説明してくれた。しかし値段が高い。広告に出ている金額とかなりの差があると指摘したら、値引きしてくれた。かなり乗り気になったのだが、話が進むにつれて怖くなってきて、ごめんなさいと言ったら怒らせてしまった。カタンとかやってるときもそうだったけど、交渉本当に下手だなと思った。

* 2021/02/25 (木)
アークナイツのイベントが始まった。喧嘩大好き部族の出身で、破天荒な、最強の女と里帰りするという話。それだけでけっこう面白い。その喧嘩大好き村に機械を持ち込んだズィママとひと悶着ある。あまり暗くならず爽やかに終わってよかった。

ケオベの茸狩迷界はめちゃくちゃ難しくて面白い。今まで使ってない低レアオペレーターを育て直すきっかけになった。目を開かされるような思い。自分が試されている、乗り越えてやろうという情熱が湧き起こる。

* 2021/02/24 (水)
「一人でできるもん」みたいな自尊心がときどき顔を出す。これを制御していきたい。

* 2021/02/23 (火)
祝日。Dragon marked for death を友人と二人で遊んでいた。動かしているだけで楽しいゲーム。グラフィックの品質としては、プレイステーション時代にでていそうなくらいだが、それが味わいがあって良い。

* 2021/02/22 (月)

あんまり仕事を割り振られないで、できることをやっていれば良いという境遇になっている。それは周りが優秀で頑張ってくれているからだ。とても良いことなんだけれど、チームの中に自分が入れてないような気がして少し寂しさも感じる。自分と活躍しているメンバーを比べると、ジメジメしている気がして。

* 2021/02/21 (日)

家探し。猫とドラゴン。

* 2021/02/20 (土)

寝ていた。

* 2021/02/19 (金)

目覚ましを無視してしまうくらい深い眠りに落ちていたらしい。気がついたときには昼休みの時間だった。予定していた打ち合わせをすっぽかしてしまっている。すっかり気が抜けて、現実を受け入れるまでに十五分はかかった。慌てて謝罪のメッセージを投稿し、そのまま会社を休むことを連絡した。昨日スーパーで買っておいたタイムセール握り寿司をパクパク食べて再び横になった。

ヨーロッパには、白鳥は死ぬときに美しい声で鳴くというという伝説が有るらしい。このことから swan song は遺作を表す比喩表現になったのだという。日本では全く使われないので何のことだかわからなかった。個人的には、白鳥の鳴き声は美しいというほどでもないと思う。

* 2021/02/18 (木)

担々麺屋へ足を運ぶ。券売機の前で、ずっと財布にひそませていた無料チケットを手にとった。お金を払わないのが申し訳ないので、トッピングしてサイドメニューも一品頼む。店員のおばさんが、明るい声でサービスしておくねと言い切った。促されるまま一円も払わずに席につく。待っている間に、無駄に嬉しくなって、この店の良いところを探してしまった。ラーメン屋というのは汚い場所が多いけどここの店はいつも清潔感あるな、と。いや、ちょろい。
