講演メモ

* リーダー

- リーダーの役割: チームの先頭に立ち、戦況を見て、戦略を決定して命令する。
- リーダーの行動: 人心掌握につとめる。

* リーダーの六つの任務

** リーダーシップ

情熱を持って、自分がありたい姿に向き合っていること。
好み・信念・理想・意志・思いを示しメンバーに理解してもらうこと。

- メンバーの理想を理解して、その実現に力を貸す
- どんなに合理的であっても、自分の考えを押し付けない
- 説得するのではなく、共感すること
- メンバーの言葉を聞いて、動くこと。聞くだけではダメ。聞いて、動くこと。
  - わかる。昔「仕事の内容について意見はないですか？」とよく意見を聞いてくれる人がいた。
    でも、自分が話をしても「なるほど、そういう意見もあるんですね」と反応して闇に吸い込まれてしまう。
    そういう経験があって、不信感を抱いてしまった。
- 部分と全体を見る。自分や他人の感情をよみとる力。ひいては社会全体の流れを見て判断する力がいる。
- 正しい倫理観・勇気を持って堂々と判断を下すことが必要。強さ、軸を持っている事が大事。
- 弱みを隠してはならない。人間味を感じる存在であることが信頼されやすい。
- ストーリを持つこと。本当に幸せだったことや辛かったことを10個ずつ振り返ると、価値観が見えてくる。

** 経営指標を把握

自分の会社の強み、弱みを理解する。
今どこにいるのかを知っていないと正しい動きができない。
売上、成長率、営業利益…など色々を知ることがそれにあたる。
自分の会社を知ると、視野が広がり、業界のことに目が向く。
より良い動きができる。

** 組織とキャリアのデザイン

会社とメンバーをどう成長させるか理想を掲げる。組織は変化していく。

** 経営と現場の意思疎通

チームと経営者の目標をすりあわせる。
経営者の意見や方針がチームに伝わるようにかみくだいて、翻訳する。

360度評価のとあるエピソード。
あるリーダーは、メンバーからの評価と自己評価はほぼ同じだが、上司からの評価は低かった。
リーダーは「メンバーの負荷を減らすために経営者と戦う」という感覚で動いていた。
最終的にクビになった。そんな話。
会社を良くしたいという心があるなら、経営者の心を理解する必要がある。

** 危機の回避

** 人事労務管理

メンタルケアだけじゃなくて勤怠状況など。
家庭の事情など不確定要素をおさえておく。
健康的に皆が働くために必要。

全体網羅された組織図を眺めると良いことが有る。
忘れていたことや、疎遠な部署があることに気づくはず。フォローできる。

苦言を呈するときは「人から聞いたんだけど」とするのではなく自分の意見にする。
「こういう場面でこういう振る舞いをするのは良くないと思った」
みたいな実体験に絡めて話すと具体的になって伝わりやすい。

* その他

** コンディションが良くないときどうするか。自分の機嫌をどうやってとる？

仕事に入る前にマインドセットする。
ずっと昔にもらったお土産に向かい合ってお祈りしたり、
今日どういうふうに過ごしていくかというのを思いふけったりする。

このルーティンを毎日やっていると、良いことがあるかもしれない。

** リーダになって欲しい人

人が好きな人。リーダーはチームメンバーとの相互理解が必要なので、人に興味を持っている人が活躍しやすい。

** かけだしのリーダーがやること

自分の理想、信念、思いとかそういうのを話す。
そのあとメンバー皆にもそういうことを話してもらう。
相互理解。
