MAC アドレスが 111111111100 であるような PC が停止しているときに
有線LAN を接続しているバイト列（マジックパケット）を送信すると、勝手に起動する。

#+begin_src
0xffffffffffff111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100111111111100
#+end_src

OSはもちろんPCも起動してない状態で、パケットを受け取れる状態にスタンバイしないといけない。
なのでハードウェア設定が必要。場合によっては BIOS の設定も必要。

そもそもパケットを送りつける機器が必要。

1. pc の電源を入れる
2. f2 連打で BIOS の設定
3. load previous values? → no
4. wake on lan のメニューはなかったので BIOS 終了
5. windows 起動
6. デバイスマネージャーを開く
7. ネットワークアダプタの中から Realtek PCle GbE Family Controller を選ぶ
8. 電源の管理
9. このデバイスでコンピュータのスタンバイを解除できるようにする
10.

https://n-archives.net/software/nwol/wol-pc-setting/bios-setting.html
https://www.iacepc.com/forum/viewtopic.php?t=779


- windows だとプライベートネットワークのファイアウォール有効にしてると ping も通らない
- リクエストしたときに飛んできてるかチェックしたい
- wireshark で確認
- https://www.tapatalk.com/groups/macrodroid/wol-wake-on-lan-t5161.html
- 0xffffffffffff[v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60][v=68:1d:ef:25:80:60]


https://www.castanet.tokyo/%E3%82%A2%E3%83%AC%E3%82%AF%E3%82%B5%E3%81%A7%E3%83%91%E3%82%BD%E3%82%B3%E3%83%B3%E3%82%92%E3%82%B7%E3%83%A3%E3%83%83%E3%83%88%E3%83%80%E3%82%A6%E3%83%B3/

これがよさそう。

arp -a コマンドでネットワークにあるデバイスの ip アドレスと MAC アドレスが見える。
ARP プロトコルで決定された結果 ARP テーブルというのが作られて、そのキャッシュ情報が出てくるらしい。

buffalo.setup (192.168.11.1) at c4:3c:ea:82:1a:58 on en0 ifscope [ethernet]
? (192.168.11.2) at f4:cf:a2:72:1c:5 on en0 ifscope [ethernet]
? (192.168.11.10) at 38:ca:73:f2:76:a on en0 ifscope [ethernet]
? (224.0.0.251) at 1:0:5e:0:0:fb on en0 ifscope permanent [ethernet]
? (239.255.255.250) at 1:0:5e:7f:ff:fa on en0 ifscope permanent [ethernet]

https://www.buffalo.jp/s3/guide/html/html/dwrhpg300nh_310/products/flist006.html

IDENT の要求
https://support.lenovo.com/by/ja/solutions/ht060840
https://qiita.com/tukiyo3/items/c801409954bead507b4a

internet 側からのping

PPPoE の話
https://www.nttpc.co.jp/column/network/pppoe_ipoe.html

DMZ の話（WAN→LANなので基本不要なはず）
http://lan-pc.pc-beginner.net/bb_router/bb_router_dmz.html

UPnP（ユニバーサルプラグアンドプレイ）
https://www.buffalo.jp/support/faq/detail/13603.html#:~:text=UPnP%E3%81%A8%E3%81%AF%E3%80%81Universal%20Plug,%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E6%A9%9F%E8%83%BD%E3%81%A7%E3%81%99%E3%80%82
デバイス検出できたりとかするみたい
